/* ═══════════════════════════════════════════════════════════════
   HiMiao · 统一语言字典 (Unified Language Dictionary)
   版本：v1.0 — 铁律架构
   
   规则：
   ① 所有翻译文本集中在此文件，禁止在业务代码中硬编码
   ② 新增翻译：在三个语言块同时添加对应 key
   ③ 禁止在此文件以外定义任何翻译字典
════════════════════════════════════════════════════════════════ */

window.HM_DICT = {
  cn: {
    'act_compare': '加入对比',
    'act_contact': '邮件联系',
    'act_detail': '查看完整审计',
    'act_pdf': '前往官网查阅原件',
    'act_share': '分享',
    'ai_greeting': '精算系统就绪。请上传保单 PDF，或输入产品代码（如 AIA-Wealth），我将为您测算真实 IRR。',
    'ai_placeholder': '输入指令，例如：帮我分析 AIA 20年 IRR…',
    'breadcrumb_current': '产品对比',
    'breadcrumb_home': '首页',
    'breadcrumb_products': '产品库',
    'btn_back': '← 返回产品库',
    'btn_clear': '清除对比',
    'btn_get': '查看审计详情',
    'btn_pro': '📊 专业模式',
    'btn_read': '阅读审计报告',
    'btn_simple': '😊 普通模式',
    'btn_view': '查看审计详情',
    'btn_compare_start': '开始详细对比',
    'tab_overview': '审计概览',
    'tab_dna': '产品 DNA',
    'tab_archive': '核心档案',
    'scenario_opt': '乐观情景',
    'scenario_neu': '中性情景',
    'scenario_pes': '悲观情景',
    'btn_booking': '📋 预约精算咨询',
    'btn_auditor_bio': '查看审计师完整简历 →',
    'btn_exit_compare': '退出对比 ✕',
    'pd_type_savings': '储蓄险 · 美元',
    'pd_src_plan': 'AIA 官方计划书原始文件 →',
    'pd_src_hkia': 'HKIA 分红实现率报告 →',
    'pd_src_annual': 'AIA 2023年报 →',
    'btn_triple_compare': '生成三方对比报告 →',
    'lbl_full_disclaimer': '查看完整声明 →',
    'calc_breakeven': '保证回本',
    'calc_breakeven_val': '第 8 年',
    'calc_btn': '生成详细推演报告',
    'calc_budget': '年度储蓄预算 (USD)',
    'calc_duration': '持有年限',
    'calc_total': '预期总价值',
    'card1_desc': '4 年实现本金安全，回本期 4 年，属全场最短，流动性窗口较早。',
    'card1_metric': '回本期: 4 年',
    'card1_title': '万通 YF · 富饶传承',
    'card2_desc': '英式分红代表作，非保证收益占比高，历史波动较大，20年 IRR 处于市场上四分位区间，非保证成分较高。',
    'card2_metric': '20年IRR: 6.15%',
    'card2_title': '保诚 · 隽富多元货币',
    'card3_desc': '高分红背后的流动性锁死风险。⚠️ 核心数据观察：前3年退保损失最高 21%，第7年达现金价值回本点。',
    'card3_metric': '前3年退保损失最高 21%',
    'card3_title': 'AIA 充裕未来 III · 流动性约束',
    'card_added': '已加入',
    'card_breakeven': '回本期',
    'card_compare': '加入对比',
    'card_irr': '年 IRR',
    'card_irr_label': '20年 IRR',
    'card_pay_prefix': '缴',
    'card_review_label': '⚖ 精算辣评 · ',
    'card_ribbon': '数据观察',
    'card_score': '综合评分',
    'card_title': '资产避险体检',
    'card_view': '查看审计详情',
    'cat_alert': '🔴 避雷预警',
    'cat_all': '全部',
    'cat_audit': '⚖ 产品审计',
    'cat_guide': '🧭 新手指南',
    'cat_market': '📊 市场情报',
    'cat_policy': '📋 政策解读',
    'ci1_desc': '涵盖108种疾病，支持多重赔付，早期重疾可独立理赔，保费豁免机制完善。',
    'ci1_metric': '保障: 108 种疾病',
    'ci1_title': '保诚 PRUlife CI 保障',
    'ci2_badge': '多重赔付: 最高 300%',
    'ci2_desc': '癌症复发额外赔付，多重赔付上限高，保终身寿险保额不减，复合保障。',
    'ci2_metric': '多重赔付: 最高 300%',
    'ci2_title': 'AIA 危疾加护保',
    'ci3_desc': '精算师团队持续更新中。订阅周报，第一时间获取新险种深度审计。',
    'ci3_metric': '敬请期待',
    'ci3_title': '更多重疾险审计报告',
    'ci_btn_list': '查看重疾险榜单',
    'ci_h2': '重疾险审计榜单',
    'ci_sub': '保障病种数 · 多重赔付 · 早期疾病覆盖',
    'clear_all': '✕  清除全部筛选',
    'clear_filter': '清除筛选条件',
    'col_add': '添加对比产品',
    'col_add_sub': '还可添加',
    'col_add_unit': '款',
    'col_remove': '移除',
    'contact_label': '联系我们',
    'cta_browse': '浏览产品库',
    'cta_email': '📮 发邮件咨询',
    'cta_h': '需要查看更多产品数据？',
    'cta_method': '了解方法论',
    'cta_pro': '查看完整数据 →',
    'cta_sub': '前往产品库浏览完整精算数据，所有数据来自保司官方披露文件',
    'disclaimer_contact': ' · 如对本声明有任何疑问，请联系',
    'disclaimer_updated': '最后更新：2026 年 2 月',
    'empty_btn': '前往产品库选择',
    'empty_msg': '没有找到匹配的产品',
    'filter_co': '保司',
    'filter_currency': '货币',
    'filter_launch_year': '上市年份',
    'filter_score': '最低评分',
    'filter_title': '险种',
    'footer_about_desc': 'HiMiao 致力于提供中立、客观的保险产品审计服务。我们不代表任何保险公司，亦不提供具体的投资建议。所有数据均源自保司公开披露文件。',
    'footer_about_title': '关于 HiMiao 审计',
    'footer_contact': '联系我们',
    'footer_copyright': '© 2026 HiMiao. 全球视野，精算未来。',
    'footer_disclaimer': '本资料不构成任何产品招揽或销售要约。本平台仅作资讯分享及教育用途。',
    'footer_privacy': '隐私条款',
    'h1': '产品对比',
    'h1_sub': '选择 2–3 款产品进行横向对比，绑色✓标记为该项数值最高',
    'hero_btn1': '查看产品精算收录库',
    'hero_btn2': '查看示例报告 (No Sign-up)',
    'hero_h1': '我们不卖保险，<br>我们只讲真话。',
    'hero_sub': 'HiMiao Audit 是独立第三方香港保险精算审计平台。在充满销售话术的行业里，我们站在消费者一侧，用精算数据说话。',
    'hero_subtitle': '不仅仅是保险。我们通过全球视野的精算审计，为您在波动中建立购买力堡垒。',
    'hero_title': '在不确定的时代，<br><span class="text-himiao">锁定</span>确定的未来',
    'hero_trust': '已收录 49 款产品 · 覆盖 13 家保司',
    'hot_label': '本周热读',
    'latest_label': '🔥 热门追踪 TOP STORIES',
    'kpi_breakeven_label': '回本年限',
    'kpi_breakeven_sub': '之前退出会亏',
    'kpi_fulfill_label': '分红实现率',
    'kpi_fulfill_sub': '过去5年平均',
    'kpi_irr_label': '20年收益率',
    'kpi_irr_sub': '含非保证红利',
    'kpi_prem_label': '缴费期',
    'kpi_prem_sub': '之后无需续缴',
    'kpi_illness_label': '病种数',
    'kpi_illness_sub': '保障病种总数',
    'kpi_early_label': '多重赔付',
    'kpi_early_sub': '是否支持多重赔付',
    'kpi_rating_label': '保司评级',
    'kpi_rating_sub': '国际信用评级',
    'kpi_loan_label': '贷款成数',
    'kpi_loan_sub': '现价质押贷款上限',
    'kpi_irr_sub_whole': '含终身寿险保障',
    'pd_breakeven_year_fmt': '第{n}年',
    'pd_growth_mult_fmt': '约 {x} 倍',
    'lbl_15yr': '15年',
    'lbl_4yr': '4年',
    'lbl_breakeven': '回本期',
    'lbl_breakeven_sub': 'Breakeven Year',
    'lbl_compare_hint': '从产品库选择竞品加入对比',
    'lbl_compare_peer': '同类产品横向对比',
    'lbl_coming_soon': '筹备中',
    'lbl_features': '核心亮点',
    'lbl_fulfill': '5年分红实现率',
    'lbl_fulfill_sub': 'Dividend Fulfillment',
    'lbl_irr': '20年 IRR',
    'lbl_irr_sub': '内部收益率',
    'lbl_ltv': '保单贷款上限',
    'lbl_ltv_sub': 'Loan LTV',
    'lbl_nonguarant': '非保证比例',
    'lbl_nonguarant_sub': '越低风险越小',
    'lbl_payment': '缴费期',
    'lbl_payment_sub': 'Payment Period',
    'lbl_review_tag': '⚖ HiMiao 精算辣评',
    'lbl_score': '综合评分',
    'lbl_score_sub': 'HiMiao Score',
    'lbl_selected_cmp': '已选对比',
    'lbl_tags': '产品标签',
    'list_method': '查看方法论',
    'list_note': '* 评分基于 HiMiao 公开审计模型计算',
    'list_title': '2026 年度精算收录库',
    'modal_added': '已加入',
    'modal_title': '添加对比产品',
    'nav_about': '关于',
    'nav_assets': '资产避险',
    'nav_health': '健康管理',
    'nav_home': '首页',
    'nav_intel': '情报站',
    'nav_legacy': '财富传承',
    'nav_news': '情报站',
    'nav_academy': 'HiMiao讲堂',
    'nav_products': '产品审计库',
    'news1_desc': '在波动的政策环境中，美联储的下一步行动将如何影响储蓄险的分红实现率？',
    'news1_title': '特朗普回归对你的美金保单意味着什么？',
    'news2_meta': '2 小时前 · 储蓄险审计组',
    'news2_tag': 'Alert ● 避雷预警',
    'news2_title': '警惕：这款“网红”分红险的回本期被隐形延长了 3 年',
    'news3_meta': '1 天前 · 医疗资源组',
    'news3_tag': 'Report ● 白皮书',
    'news3_title': '2026 香港重疾险审计：你真的需要“多重赔付”吗？',
    'news_main_title': 'HiMiao讲堂',
    'news_page_h1': '市场资讯',
    'news_view_all': '进入讲堂',
    'next_page': '下一页 →',
    'page_h1': '全球资产审计库',
    'page_sub': '由 HiMiao 精算团队独立出品 · 不带货 · 只讲真话',
    'page_title': '关于 HiMiao | 独立精算审计平台',
    'prev_page': '← 上一页',
    'q1_ans': '非常安全',
    'q1_label': '① 安全吗？',
    'q2_label': '② 钱会增值吗？',
    'q3_ans': '前期不能取',
    'q3_label': '③ 有什么风险？',
    'read_full': '阅读完整审计 →',
    'result_count': '显示 {n} 款产品',
    'search_ph': '搜索文章…',
    'sub_ph': '您的邮箱',
    'sec_actuarial': '精算核心数据',
    'sec_basic': '基本信息',
    'sec_compliance': '合规披露指标',
    'sec_features': '特色功能',
    'sec_review': '精算辣评',
    'sort_breakeven': '回本期（快→慢）',
    'sort_irr': '20年 IRR（高→低）',
    'sort_score': '综合评分（高→低）',
    'stat1': '已审计产品',
    'stat2': '精算师平均年限',
    'stat3': '与保司销售合作',
    'stat4': '险种覆盖',
    'sub_btn': '订阅',
    'sub_err': '请输入有效的邮箱地址',
    'sub_success': '✓ 订阅成功！',
    'sub_desc': '每周一发送。只讲真话，不含广告。',
    'sub_h': '订阅审计周报',
    'sub_note': '已有 2,847 位读者 · 随时可退订',
    'sub_title': '订阅审计周报',
    'suit_c1': '能持有 10 年以上',
    'suit_c1_sub': '这笔钱 10 年内不打算动用',
    'suit_c2': '接受非保证红利波动',
    'suit_c3': '需要持有美元资产',
    'suit_h': '流动性检核 — 关键数据',
    'suit_sub': '以下为客观数据指标，不构成个人适配建议',
    'tab_ci': '重疾险',
    'tab_whole_life': '终身寿险',
    'tab_wholelife': '终身寿险',
    'tab_savings': '储蓄分红险',
    'toast_dupe': '该产品已在对比中',
    'toast_max': '最多对比 3 款产品',
    'toast_min_select': '请至少选择 2 款产品进行对比',
    'val_higher': '▲ 数值较高',
    'val_lower': '▼ 数值较低',
    'val_year': '年',
    'card2_badge': '英式分红 · IRR 上四分位',
    'card3_badge': '⚠ 早期退保高损',
    'card3_tooltip': '触发条件：前3年累计现金价值 &lt; 已缴保费的 79%<br>数据来源：保司官方建议书现金价值表',
    'calc_model_badge': '[静态模型] 30岁 · 男 · 非吸烟',
    'calc_disclaimer': '本沙盘基于统一模型进行数学推演，不构成任何财务适配建议',
    'footer_nav_title': '导航',
    'footer_contact_title': '联系',
    'wl1_title': 'AIA 乐怡人生（终期红利）',
    'wl1_desc': '10年缴，至70年保单现金价值约21.7倍已缴保费，长期复利效应显著，终期红利不可锁定。',
    'wl1_metric': '70年: 21.7x 已缴保费',
    'wl1_btn': '查看终身寿险数据',
    'wl2_badge': '红利可锁定 · 身故不递减',
    'wl2_title': '永明 佐佑传承 II',
    'wl2_desc': '周年红利+终期红利双重积累，终期红利可锁定增值，身故保额全程不递减，财富传承效应显著。',
    'wl2_metric': '30年: 2.9x · 70年: 14x+',
    'wl3_badge': '⚠ 注意死亡保障递减',
    'wl3_company': 'WHOLE LIFE · 部分产品',
    'wl3_title': '身故保额递减条款',
    'wl3_desc': '部分终身寿险设有保额递减条款，晚年身故保障可降至保额50%以下，适合以储蓄传承为主要诉求的投保人。',
    'wl3_metric': '递减下限: 保额 50%',
    'wl3_btn': '查看完整数据',
    'ci3_waiting_badge': '⚠ 注意等待期',
    'ci3_waiting_company': 'CI · 数据观察',
    'ci3_waiting_title': '等待期与首年免责条款',
    'ci3_waiting_desc': '本样本11款重疾险中，标准等待期90天，部分附加癌症险等待期延至180天，首次确诊日计算方式各家不一致。',
    'ci3_waiting_metric': '等待期: 90–180 天',
    'ci3_waiting_btn': '查看完整数据对比',
    'why_h2': '香港保险市场，<br>信息严重不对称',
    'why_label': '为什么存在',
    'about_hero_label': '关于 HiMiao',
    'about_why_p1': '一张储蓄分红险计划书，少则几十页，多则上百页。保证收益和非保证收益混排，IRR 被刻意模糊，回本期的定义各家保司不统一。',
    'about_why_p2': '普通消费者没有时间、没有工具、也没有精算知识，去穿透这些信息。于是他们只能依赖经纪人——而经纪人的收入来自佣金。',
    'about_why_p3': 'HiMiao 的存在，是为了打破这个循环。我们是消费者在这个市场里的精算师。',
    'about_principles_label': '核心原则',
    'about_p1_title': '数据先于观点',
    'about_p1_desc': '所有结论来自计算，不来自主观判断。每个数字都有原始出处。',
    'about_p2_title': '无销售立场',
    'about_p2_desc': '不存在佣金分成。好的说好，有风险的点明。',
    'about_p3_title': '让普通人看懂',
    'about_p3_desc': '把精算结论翻译成任何人都能理解的语言。',
    'about_p4_title': '持续更新',
    'about_p4_desc': '随保司条款更新同步，不发布过时审计报告。',
    'about_process_label': '精算审计流程',
    'about_process_h2': '每一份审计报告，<br>都经过四道关卡',
    'about_process_intro': '从原始计划书到产品库展示，我们的审计流程经过精算师、数据工程师与 AI 引擎的三重把关，确保每一个数字的准确性。',
    'about_step1_title': '采集与数字化',
    'about_step1_desc': '从保司官方《利益说明文件》精准提取原始数据，严格分离「保证金额」与「非保证金额」两列。',
    'about_step2_title': '人工清洗校验',
    'about_step2_desc': '数据专员逐行比对原始计划书，纠正 OCR 误读，确保年份与数值严格对应，防止错位。',
    'about_step3_title': 'AI 精算核验',
    'about_step3_badge': '核心护城河',
    'about_step3_desc': '算法引擎自动反推 IRR，检测曲线平滑性，验证回本期合理性。不通过则驳回重审。',
    'about_step4_title': '自动发布上架',
    'about_step4_desc': '通过核验后生成标准化 JSON，推送至产品库。整个流程最快 24 小时完成。',
    'about_contact_h2': '有问题，来找我们',
    'about_contact_intro': '无论是产品数据勘误、精算合作申请，还是想了解 HiMiao，欢迎联系。',
    'about_contact_email': '电子邮件',
    'about_contact_email_reply': '通常 24–48 小时内回复',
    'about_contact_wechat': '微信',
    'about_contact_wechat_qr': '扫码添加，备注「HiMiao」',
    'about_contact_we_response': '我们会回应什么',
    'about_contact_ok1': '产品数据勘误反馈',
    'about_contact_ok2': '精算审计合作申请',
    'about_contact_ok3': '媒体引用与授权',
    'about_contact_ok4': '经纪人平台合作',
    'about_contact_no': '产品推销（无此业务）',
    'about_disc_label': '法律声明与免责条款',
    'about_disc_h2': '完整免责声明',
    'about_disc_1_h3': '1 · 平台性质',
    'about_disc_1_p': 'HiMiao Audit（「本平台」）为独立第三方保险信息审计平台，由 HiMiao 团队独立运营。本平台与任何持牌保险公司、持牌保险经纪人或持牌保险代理人不存在任何形式的销售合作、佣金分成或利益关联关系。',
    'about_disc_2_h3': '2 · 信息性质与使用限制',
    'about_disc_2_p': '本平台所有内容（包括但不限于产品审计报告、精算数据、IRR 计算结果、评分系统、编辑评论及情报站文章）仅供一般信息参考用途。上述内容不构成任何形式的投资建议、财务建议、保险购买建议或任何专业意见，亦不构成对任何保险产品的招揽或推介。',
    'about_disc_3_h3': '3 · 数据来源与准确性',
    'about_disc_3_p': '本平台数据主要来源于相关保险公司官方《利益说明文件》、香港保险业监管局（HKIA）公开披露资料。本平台已采取合理措施确保数据准确性，但不对任何数据的完整性、时效性或准确性作出保证。保险产品条款、收益假设及分红政策可能随时变更，请以相关保险公司最新官方文件为准。',
    'about_disc_4_h3': '4 · IRR 及收益演示说明',
    'about_disc_4_p': '本平台展示的 IRR（内部收益率）数据及现金价值演示均基于特定假设条件计算，包含非保证收益部分。非保证收益不代表实际将获得的收益，实际结果可能与演示存在重大差异。过往分红实现率不构成对未来分红表现的保证或预测。',
    'about_disc_5_h3': '5 · 专业建议声明',
    'about_disc_5_p': '在作出任何保险购买决定前，请寻求持牌保险顾问、财务规划师或其他相关专业人士的独立专业意见，并仔细阅读相关保险产品的完整条款及细则。',
    'about_disc_6_h3': '6 · 知识产权',
    'about_disc_6_p': '本平台所有原创内容的知识产权归 HiMiao 团队所有。未经书面授权，不得以任何形式复制、转载或商业使用。媒体引用请联系',
    'about_disc_7_h3': '7 · 隐私政策',
    'about_disc_7_p': '本平台收集的用户信息（包括订阅邮箱）仅用于发送本平台内容推送，不会出售、转让或以任何商业目的向第三方披露。用户可随时通过邮件要求删除个人信息。本平台不使用追踪性广告 Cookie。',
    'about_disc_8_h3': '8 · 适用法律',
    'about_disc_8_p': '本平台服务条款及免责声明受香港特别行政区法律管辖。如有任何争议，以香港特别行政区法院为解决争议的司法管辖地。',
    'about_region_banner': '【区域提示】本平台仅提供公开精算数据模型展示，不面向中国内地开展任何保险推介、报告下载或业务引导服务。',
    'loading_msg': '加载中…',
    'error_load_fail': '加载失败',
    'error_refresh_hint': '请刷新页面重试',
    'btn_reload': '重新加载',
    'top_stories': '今日要闻',
    'sub_free': '免费订阅',
    'empty_articles': '没有找到相关文章',
    'view_all_articles': '查看全部文章',
    'no_content': '暂无正文内容',
    'filter_btn_filter': '筛选',
    'filter_btn_close': '关闭',
    'filter_update': '数据更新',
    'no_data': '暂无精算备注',
    'tag_discontinued': '已停售',
    'tag_onsale': '在售',
    'sort_name_az': '产品名称（A→Z）',
    'metric_covered': '保障病种',
    'metric_prem_years': '缴费年期',
    'metric_multi_pay': '多重赔付',
    'metric_annual_prem': '年缴保费',
    'article_loading': '正在加载…',
    'article_not_found': '文章未找到',
    'article_error_hint': '该文章可能已下架或链接有误',
    'back_to_news': '返回 HiMiao讲堂',
    'related_products': '相关产品数据',
    'related_products_desc': '读完情报，查阅精算审计过的客观产品数据。',
    'cta_products': '进入产品审计库 →',
    'submitting': '提交中…',
    'sub_fail': '订阅失败，请稍后重试',
    'article_no_slug': '未指定文章，请从 HiMiao讲堂 列表进入',
    'article_not_exist': '文章不存在或已下架',
    'no_more_articles': '暂无其他文章',
    'pd_load_ing': '正在加载产品数据…',
    'pd_load_fail': '加载失败',
    'pd_not_found': '产品不存在或未发布',
    'pd_back': '← 返回产品库',
    'pd_product_detail': '产品详情',
    'pd_data_loading': '保司信息加载中…',
    'pd_static_model': '【静态模型声明】本页测算基于全市场统一标准样本（30岁非吸烟男性），展示20年参考数据。不构成针对个人的财务适配建议。如需针对个人情况的专业评估，请咨询持牌保险顾问。',
    'pd_type_whole_life': '终身寿险',
    'pd_type_critical_illness': '重疾险',
    'pd_meta_term': '条款版本',
    'pd_meta_denom': '计价资产',
    'pd_data_version': '数据版本',
    'pd_q1_body': '保司信用评级 {rating}，全球前10%。资产受香港保险业监管局监管，设有保单持有人保障基金。',
    'pd_q2_sub': '持有 20 年参考值',
    'pd_q2_sub_whole': '持有 20 年（含终身保障）',
    'pd_q2_sub_ci': '保障重症+早期危疾',
    'pd_q2_body_ci_multi': '覆盖 <strong>{count}</strong> 种疾病，支持<strong>多重赔付</strong>，癌症可多次理赔。',
    'pd_q2_body_ci_single': '覆盖 <strong>{count}</strong> 种疾病，单次赔付，理赔后保单终止。',
    'pd_q2_body': '年化收益率约 {irr}，含非保证红利。具体收益参考精算审计指标。',
    'pd_q3_body': '前 {n} 年退保会亏损。前 {n} 年内退保将产生本金损失，请参阅现金价值表。',
    'pd_suit_c2_sub': '实际收益可能高于或低于演示值。',
    'pd_suit_c3_sub': '这款产品以美元计价，汇率会影响实际收益。',
    'pd_badge_div_savings': '分红型',
    'pd_badge_div_life': '终身保障',
    'pd_rating_suffix': '评级',
    'pd_currency_usd': '美元',
    'pd_currency_hkd': '港元',
    'pd_ai_extract': '⚠ AI 辅助提取数据 — 本页精算数值由 OCR 技术从官方文件中提取，可能存在细微偏差。精准数值请以各保司官方建议书为准。',
    'pd_type_savings': '储蓄险',
    'pd_usd': '美元计价',
    'pd_dividend': '分红型',
    'pd_rating_aa': 'AA+ 评级',
    'pd_wechat': '微信咨询',
    'pd_wechat_add': '添加微信，免费咨询持牌顾问',
    'pd_close': '关闭',
    'pd_verdict': '精算审计结论',
    'pd_risk': '风险提示',
    'pd_baseline': '核心测算基准',
    'pd_baseline_sub': '统一静态模型假设',
    'pd_label_gender': '性别',
    'pd_label_age': '年龄',
    'pd_label_smoke': '吸烟史',
    'pd_male': '男',
    'pd_female': '女',
    'pd_nonsmoke': '非吸烟',
    'pd_consult': '💬 咨询持牌保险顾问',
    'pd_consult_desc': '数据仅供参考，个人情况差异较大。持牌顾问可为你提供合规的个人化评估。',
    'pd_wechat_cta': '🟢 微信免费咨询 →',
    'pd_review': '精算备注',
    'pd_toast_compare': '请从产品库选择第二款产品，点击「加入对比」即可开启双产品对比模式',
    'pd_toast_copied': '✓ 链接已复制到剪贴板',
    'pd_toast_manual': '请手动复制浏览器地址栏链接',
    'cmp_dim': '对比维度 / Comparison Metrics',
    'cmp_feature': '核心亮点',
    'cmp_score': '综合评分',
    'cmp_currency': '保单币种',
    'cmp_pending': '待更新',
    'cmp_no_data': '暂无数据',
    'cmp_pending_in': '待录入',
    'cmp_support': '支持',
    'cmp_no_support': '不支持',
    'cmp_confirm': '待确认',
    'cmp_mixed_warn': '⚠ 当前对比包含不同险种产品，建议选择同类产品以获得精准对比维度',
    'cmp_basic': '基本信息',
    'cmp_actuarial': '精算核心',
    'cmp_compliance': '合规披露',
    'cmp_features': '产品特色',
    'cmp_tags': '特色标签',
    'cmp_coverage': '保障内容',
    'cmp_verdict': '精算辣评',
    'cmp_payment_term': '缴费年期',
    'cmp_irr20': '20年 IRR',
    'cmp_breakeven': '保证回本年',
    'cmp_fulfill5y': '近5年分红实现率',
    'cmp_loan_ltv': '保单贷款上限',
    'cmp_annual_prem': '年缴保费',
    'cmp_conditions': '涵盖重疾病种数',
    'cmp_multi_pay': '多重赔付',
    'cmp_view_audit': '查看审计详情 →',
    'cmp_year_cash': '第{n}年现金价值'
  },
  hk: {
    'act_compare': '加入對比',
    'act_contact': '電郵聯絡',
    'act_detail': '查看完整審計',
    'act_pdf': '前往官網查閱原件',
    'act_share': '分享',
    'ai_greeting': '精算系統就緒。請上傳保單 PDF，或輸入產品代碼（如 AIA-Wealth），我將為您測算真實 IRR。',
    'ai_placeholder': '輸入指令，例如：幫我分析 AIA 20年 IRR…',
    'breadcrumb_current': '產品對比',
    'breadcrumb_home': '首頁',
    'breadcrumb_products': '產品庫',
    'btn_back': '← 返回產品庫',
    'btn_clear': '清除對比',
    'btn_get': '查看審計詳情',
    'btn_pro': '📊 專業模式',
    'btn_read': '閱讀審計報告',
    'btn_simple': '😊 普通模式',
    'btn_view': '查看審計詳情',
    'btn_compare_start': '開始詳細對比',
    'tab_overview': '審計概覽',
    'tab_dna': '產品 DNA',
    'tab_archive': '核心檔案',
    'scenario_opt': '樂觀情景',
    'scenario_neu': '中性情景',
    'scenario_pes': '悲觀情景',
    'btn_booking': '📋 預約精算諮詢',
    'btn_auditor_bio': '查看審計師完整簡歷 →',
    'btn_exit_compare': '退出對比 ✕',
    'pd_type_savings': '儲蓄險 · 美元',
    'pd_src_plan': 'AIA 官方計劃書原始文件 →',
    'pd_src_hkia': 'HKIA 分紅實現率報告 →',
    'pd_src_annual': 'AIA 2023年報 →',
    'btn_triple_compare': '生成三方對比報告 →',
    'lbl_full_disclaimer': '查看完整聲明 →',
    'calc_breakeven': '保證回本',
    'calc_breakeven_val': '第 8 年',
    'calc_btn': '生成詳細推演報告',
    'calc_budget': '假設年繳保費 (USD)',
    'calc_duration': '持有年限',
    'calc_total': '預期總價值',
    'card1_desc': '4 年實現本金安全，回本期 4 年屬全場最短，流動性窗口較早。',
    'card1_metric': '回本期: 4 年',
    'card1_title': '萬通 YF · 富饒傳承',
    'card2_desc': '英式分紅代表作，非保證收益佔比高，歷史波動較大，20年 IRR 處於市場上四分位區間，非保證成分較高。',
    'card2_metric': '20年IRR: 6.15%',
    'card2_title': '保誠 · 雋富多元貨幣',
    'card3_desc': '高分紅背後的流動性鎖死風險。⚠️ 核心數據觀察：前3年退保損失最高 21%，第7年達現金價值回本點。',
    'card3_metric': '前3年退保損失最高 21%',
    'card3_title': 'AIA 充裕未來 III · 流動性約束',
    'card_added': '已加入',
    'card_breakeven': '回本期',
    'card_compare': '加入對比',
    'card_irr': '年 IRR',
    'card_irr_label': '20年 IRR',
    'card_pay_prefix': '繳',
    'card_review_label': '⚖ 精算辣評 · ',
    'card_ribbon': '編輯精選',
    'card_score': '綜合評分',
    'card_title': '資產避險體檢',
    'card_view': '查看審計詳情',
    'cat_alert': '🔴 避雷預警',
    'cat_all': '全部',
    'cat_audit': '⚖ 產品審計',
    'cat_guide': '🧭 新手指南',
    'cat_market': '📊 市場情報',
    'cat_policy': '📋 政策解讀',
    'ci1_desc': '涵蓋108種疾病，支持多重賠付，早期重疾可獨立理賠，保費豁免機制完善。',
    'ci1_metric': '保障: 108 種疾病',
    'ci1_title': '保誠 PRUlife CI 保障',
    'ci2_badge': '多重賠付: 最高 300%',
    'ci2_desc': '癌症復發額外賠付，多重賠付上限高，保終身壽險保額不減，複合保障。',
    'ci2_metric': '多重賠付: 最高 300%',
    'ci2_title': 'AIA 危疾加護保',
    'ci3_desc': '精算師團隊持續更新中。訂閱週報，第一時間獲取新險種深度審計。',
    'ci3_metric': '敬請期待',
    'ci3_title': '更多重疾險審計報告',
    'ci_btn_list': '查看重疾險榜單',
    'ci_h2': '重疾險審計榜單',
    'ci_sub': '保障病種數 · 多重賠付 · 早期疾病覆蓋',
    'clear_all': '✕  清除全部篩選',
    'clear_filter': '清除篩選條件',
    'col_add': '新增對比產品',
    'col_add_sub': '還可新增',
    'col_add_unit': '款',
    'col_remove': '移除',
    'contact_label': '聯絡我們',
    'cta_browse': '瀏覽產品庫',
    'cta_email': '📮 發郵件諮詢',
    'cta_h': '需要查看更多產品數據？',
    'cta_method': '了解方法論',
    'cta_pro': '查看完整數據 →',
    'cta_sub': '前往產品庫瀏覽完整精算數據，所有數據來自保司官方披露文件',
    'disclaimer_contact': ' · 如對本聲明有任何疑問，請聯絡',
    'disclaimer_updated': '最後更新：2026 年 2 月',
    'empty_btn': '前往產品庫選擇',
    'empty_msg': '沒有找到匹配的產品',
    'filter_co': '保司',
    'filter_currency': '貨幣',
    'filter_launch_year': '上市年份',
    'filter_score': '最低評分',
    'filter_title': '險種',
    'footer_about_desc': 'HiMiao 致力於提供中立、客觀的保險產品審計服務。我們不代表任何保險公司，亦不提供具體的投資建議。所有數據均源自保司公開披露文件。',
    'footer_about_title': '關於 HiMiao 審計',
    'footer_contact': '聯繫我們',
    'footer_copyright': '© 2026 HiMiao. 全球視野，精算未來。',
    'footer_disclaimer': '本資料不構成任何產品招攬或銷售要約。本平台僅作資訊分享及教育用途。',
    'footer_privacy': '隱私條款',
    'h1': '產品對比',
    'h1_sub': '選擇 2–3 款產品進行橫向對比，綠色標記為該項數值較高',
    'hero_btn1': '查看旗艦產品收錄庫',
    'hero_btn2': '查看示例報告 (No Sign-up)',
    'hero_h1': '我們不賣保險，<br>我們只講真話。',
    'hero_sub': 'HiMiao Audit 是獨立第三方香港保險精算審計平台。在充滿銷售話術的行業裡，我們站在消費者一側，用精算數據說話。',
    'hero_subtitle': '不僅僅是保險。我們通過全球視野的精算審計，為您在波動中建立購買力堡壘。',
    'hero_title': '在不確定的時代，<br><span class="text-himiao">鎖定</span>確定的未來',
    'hero_trust': '已收錄 49 款產品 · 覆蓋 13 家保司',
    'hot_label': '本週熱讀',
    'latest_label': '🔥 熱門追蹤 TOP STORIES',
    'kpi_breakeven_label': '回本年限',
    'kpi_breakeven_sub': '之前退出會虧',
    'kpi_fulfill_label': '分紅實現率',
    'kpi_fulfill_sub': '過去5年平均',
    'kpi_irr_label': '20年收益率',
    'kpi_irr_sub': '含非保證紅利',
    'kpi_prem_label': '繳費期',
    'kpi_prem_sub': '之後無需續繳',
    'kpi_illness_label': '病種數',
    'kpi_illness_sub': '保障病種總數',
    'kpi_early_label': '多重賠付',
    'kpi_early_sub': '是否支持多重賠付',
    'kpi_rating_label': '保司評級',
    'kpi_rating_sub': '國際信用評級',
    'kpi_loan_label': '貸款成數',
    'kpi_loan_sub': '現價質押貸款上限',
    'kpi_irr_sub_whole': '含終身壽險保障',
    'pd_breakeven_year_fmt': '第{n}年',
    'pd_growth_mult_fmt': '約 {x} 倍',
    'lbl_15yr': '15年',
    'lbl_4yr': '4年',
    'lbl_breakeven': '回本期',
    'lbl_breakeven_sub': 'Breakeven Year',
    'lbl_compare_hint': '從產品庫選擇競品加入對比',
    'lbl_compare_peer': '同類產品橫向對比',
    'lbl_coming_soon': '籌備中',
    'lbl_features': '核心亮點',
    'lbl_fulfill': '5年分紅實現率',
    'lbl_fulfill_sub': 'Dividend Fulfillment',
    'lbl_irr': '20年 IRR',
    'lbl_irr_sub': '內部回報率',
    'lbl_ltv': '保單貸款上限',
    'lbl_ltv_sub': 'Loan LTV',
    'lbl_nonguarant': '非保證比例',
    'lbl_nonguarant_sub': '越低風險越小',
    'lbl_payment': '繳費期',
    'lbl_payment_sub': 'Payment Period',
    'lbl_review_tag': '⚖ HiMiao 精算點評',
    'lbl_score': '綜合評分',
    'lbl_score_sub': 'HiMiao Score',
    'lbl_selected_cmp': '已選對比',
    'lbl_tags': '產品標籤',
    'list_method': '查看方法論',
    'list_note': '* 評分基於 HiMiao 公開審計模型計算',
    'list_title': '2026 年度精算收錄庫',
    'modal_added': '已加入',
    'modal_title': '新增對比產品',
    'nav_about': '關於',
    'nav_assets': '資產避險',
    'nav_health': '健康管理',
    'nav_home': '首頁',
    'nav_intel': '情報站',
    'nav_legacy': '財富傳承',
    'nav_news': '情報站',
    'nav_academy': 'HiMiao讲堂',
    'nav_products': '產品審計庫',
    'news1_desc': '在波動的政策環境中，美聯儲的下一步行動將如何影響儲蓄險的分紅實現率？',
    'news1_title': '特朗普回歸對你的美金保單意味著什麼？',
    'news2_meta': '2 小時前 · 儲蓄險審計組',
    'news2_tag': 'Alert ● 避雷預警',
    'news2_title': '警惕：這款“網紅”分紅險的回本期被隱形延長了 3 年',
    'news3_meta': '1 天前 · 醫療資源組',
    'news3_tag': 'Report ● 白皮書',
    'news3_title': '2026 香港重疾險審計：你真的需要“多重賠付”嗎？',
    'news_main_title': 'HiMiao讲堂',
    'news_page_h1': '市場資訊',
    'news_view_all': '進入講堂',
    'next_page': '下一頁 →',
    'page_h1': '全球資產審計庫',
    'page_sub': '由 HiMiao 精算團隊獨立出品 · 不帶貨 · 只講真話',
    'page_title': '關於 HiMiao | 獨立精算審計平台',
    'prev_page': '← 上一頁',
    'q1_ans': '非常安全',
    'q1_label': '① 安全嗎？',
    'q2_label': '② 錢會增值嗎？',
    'q3_ans': '前期不能取',
    'q3_label': '③ 有什麼風險？',
    'read_full': '閱讀完整審計 →',
    'result_count': '顯示 {n} 款產品',
    'search_ph': '搜尋文章…',
    'sub_ph': '您的郵箱',
    'sec_actuarial': '精算核心數據',
    'sec_basic': '基本資訊',
    'sec_compliance': '合規披露指標',
    'sec_features': '特色功能',
    'sec_review': '精算點評',
    'sort_breakeven': '回本期（快→慢）',
    'sort_irr': '20年 IRR（高→低）',
    'sort_score': '綜合評分（高→低）',
    'stat1': '已審計產品',
    'stat2': '精算師平均年限',
    'stat3': '與保司銷售合作',
    'stat4': '險種覆蓋',
    'sub_btn': '訂閱',
    'sub_err': '請輸入有效的郵箱地址',
    'sub_success': '✓ 訂閱成功！',
    'sub_desc': '每週一發送。只講真話，不含廣告。',
    'sub_h': '訂閱審計週報',
    'sub_note': '已有 2,847 位讀者 · 隨時可退訂',
    'sub_title': '訂閱審計週報',
    'suit_c1': '能持有 10 年以上',
    'suit_c1_sub': '這筆錢 10 年內不打算動用',
    'suit_c2': '接受非保證紅利波動',
    'suit_c3': '需要持有美元資產',
    'suit_h': '流動性檢核 — 關鍵數據',
    'suit_sub': '以下為客觀數據指標，不構成個人適配建議',
    'tab_ci': '重疾險',
    'tab_whole_life': '終身壽險',
    'tab_wholelife': '終身壽險',
    'tab_savings': '儲蓄分紅險',
    'toast_dupe': '該產品已在對比中',
    'toast_max': '最多對比 3 款產品',
    'toast_min_select': '請至少選擇 2 款產品進行對比',
    'val_higher': '▲ 數值較高',
    'val_lower': '▼ 數值較低',
    'val_year': '年',
    'card2_badge': '英式分紅 · IRR 上四分位',
    'card3_badge': '⚠ 早期退保高損',
    'card3_tooltip': '觸發條件：前3年累計現金價值 &lt; 已繳保費的 79%<br>數據來源：保司官方建議書現金價值表',
    'calc_model_badge': '[靜態模型] 30歲 · 男 · 非吸煙',
    'calc_disclaimer': '本沙盤基於統一模型進行數學推演，不構成任何財務適配建議',
    'footer_nav_title': '導航',
    'footer_contact_title': '聯繫',
    'wl1_title': 'AIA 樂怡人生（終期紅利）',
    'wl1_desc': '10年繳，至70年保單現金價值約21.7倍已繳保費，長期複利效應顯著，終期紅利不可鎖定。',
    'wl1_metric': '70年: 21.7x 已繳保費',
    'wl1_btn': '查看終身壽險數據',
    'wl2_badge': '紅利可鎖定 · 身故不遞減',
    'wl2_title': '永明 佐佑傳承 II',
    'wl2_desc': '周年紅利+終期紅利雙重積累，終期紅利可鎖定增值，身故保額全程不遞減，財富傳承效應顯著。',
    'wl2_metric': '30年: 2.9x · 70年: 14x+',
    'wl3_badge': '⚠ 注意死亡保障遞減',
    'wl3_company': 'WHOLE LIFE · 部分產品',
    'wl3_title': '身故保額遞減條款',
    'wl3_desc': '部分終身壽險設有保額遞減條款，晚年身故保障可降至保額50%以下，適合以儲蓄傳承為主要訴求的投保人。',
    'wl3_metric': '遞減下限: 保額 50%',
    'wl3_btn': '查看完整數據',
    'ci3_waiting_badge': '⚠ 注意等待期',
    'ci3_waiting_company': 'CI · 數據觀察',
    'ci3_waiting_title': '等待期與首年免責條款',
    'ci3_waiting_desc': '本樣本11款重疾險中，標準等待期90天，部分附加癌症險等待期延至180天，首次確診日計算方式各家不一致。',
    'ci3_waiting_metric': '等待期: 90–180 天',
    'ci3_waiting_btn': '查看完整數據對比',
    'why_h2': '香港保險市場，<br>資訊嚴重不對稱',
    'why_label': '為什麼存在',
    'about_hero_label': '關於 HiMiao',
    'about_why_p1': '一張儲蓄分紅險計劃書，少則幾十頁，多則上百頁。保證收益和非保證收益混排，IRR 被刻意模糊，回本期的定義各家保司不統一。',
    'about_why_p2': '普通消費者沒有時間、沒有工具、也沒有精算知識，去穿透這些資訊。於是他們只能依賴經紀人——而經紀人的收入來自佣金。',
    'about_why_p3': 'HiMiao 的存在，是為了打破這個循環。我們是消費者在這個市場裡的精算師。',
    'about_principles_label': '核心原則',
    'about_p1_title': '數據先於觀點',
    'about_p1_desc': '所有結論來自計算，不來自主觀判斷。每個數字都有原始出處。',
    'about_p2_title': '無銷售立場',
    'about_p2_desc': '不存在佣金分成。好的說好，有風險的點明。',
    'about_p3_title': '讓普通人看懂',
    'about_p3_desc': '把精算結論翻譯成任何人都能理解的語言。',
    'about_p4_title': '持續更新',
    'about_p4_desc': '隨保司條款更新同步，不發布過時審計報告。',
    'about_process_label': '精算審計流程',
    'about_process_h2': '每一份審計報告，<br>都經過四道關卡',
    'about_process_intro': '從原始計劃書到產品庫展示，我們的審計流程經過精算師、數據工程師與 AI 引擎的三重把關，確保每一個數字的準確性。',
    'about_step1_title': '採集與數位化',
    'about_step1_desc': '從保司官方《利益說明文件》精準提取原始數據，嚴格分離「保證金額」與「非保證金額」兩列。',
    'about_step2_title': '人工清洗校驗',
    'about_step2_desc': '數據專員逐行比對原始計劃書，糾正 OCR 誤讀，確保年份與數值嚴格對應，防止錯位。',
    'about_step3_title': 'AI 精算核驗',
    'about_step3_badge': '核心護城河',
    'about_step3_desc': '演算法引擎自動反推 IRR，檢測曲線平滑性，驗證回本期合理性。不通過則駁回重審。',
    'about_step4_title': '自動發布上架',
    'about_step4_desc': '通過核驗後生成標準化 JSON，推送至產品庫。整個流程最快 24 小時完成。',
    'about_contact_h2': '有問題，來找我們',
    'about_contact_intro': '無論是產品數據勘誤、精算合作申請，還是想了解 HiMiao，歡迎聯繫。',
    'about_contact_email': '電子郵件',
    'about_contact_email_reply': '通常 24–48 小時內回覆',
    'about_contact_wechat': '微信',
    'about_contact_wechat_qr': '掃碼添加，備註「HiMiao」',
    'about_contact_we_response': '我們會回應什麼',
    'about_contact_ok1': '產品數據勘誤反饋',
    'about_contact_ok2': '精算審計合作申請',
    'about_contact_ok3': '媒體引用與授權',
    'about_contact_ok4': '經紀人平台合作',
    'about_contact_no': '產品推銷（無此業務）',
    'about_disc_label': '法律聲明與免責條款',
    'about_disc_h2': '完整免責聲明',
    'about_disc_1_h3': '1 · 平台性質',
    'about_disc_1_p': 'HiMiao Audit（「本平台」）為獨立第三方保險資訊審計平台，由 HiMiao 團隊獨立營運。本平台與任何持牌保險公司、持牌保險經紀人或持牌保險代理人不存在任何形式的銷售合作、佣金分成或利益關聯關係。',
    'about_disc_2_h3': '2 · 資訊性質與使用限制',
    'about_disc_2_p': '本平台所有內容（包括但不限於產品審計報告、精算數據、IRR 計算結果、評分系統、編輯評論及情報站文章）僅供一般資訊參考用途。上述內容不構成任何形式的投資建議、財務建議、保險購買建議或任何專業意見，亦不構成對任何保險產品的招攬或推介。',
    'about_disc_3_h3': '3 · 數據來源與準確性',
    'about_disc_3_p': '本平台數據主要來源於相關保險公司官方《利益說明文件》、香港保險業監管局（HKIA）公開披露資料。本平台已採取合理措施確保數據準確性，但不對任何數據的完整性、時效性或準確性作出保證。保險產品條款、收益假設及分紅政策可能隨時變更，請以相關保險公司最新官方文件為準。',
    'about_disc_4_h3': '4 · IRR 及收益演示說明',
    'about_disc_4_p': '本平台展示的 IRR（內部收益率）數據及現金價值演示均基於特定假設條件計算，包含非保證收益部分。非保證收益不代表實際將獲得的收益，實際結果可能與演示存在重大差異。過往分紅實現率不構成對未來分紅表現的保證或預測。',
    'about_disc_5_h3': '5 · 專業建議聲明',
    'about_disc_5_p': '在作出任何保險購買決定前，請尋求持牌保險顧問、財務規劃師或其他相關專業人士的獨立專業意見，並仔細閱讀相關保險產品的完整條款及細則。',
    'about_disc_6_h3': '6 · 知識產權',
    'about_disc_6_p': '本平台所有原創內容的知識產權歸 HiMiao 團隊所有。未經書面授權，不得以任何形式複製、轉載或商業使用。媒體引用請聯繫',
    'about_disc_7_h3': '7 · 隱私政策',
    'about_disc_7_p': '本平台收集的用戶資訊（包括訂閱郵箱）僅用於發送本平台內容推送，不會出售、轉讓或以任何商業目的向第三方披露。用戶可隨時通過郵件要求刪除個人資訊。本平台不使用追蹤性廣告 Cookie。',
    'about_disc_8_h3': '8 · 適用法律',
    'about_disc_8_p': '本平台服務條款及免責聲明受香港特別行政區法律管轄。如有任何爭議，以香港特別行政區法院為解決爭議的司法管轄地。',
    'about_region_banner': '【區域提示】本平台僅提供公開精算數據模型展示，不面向中國內地開展任何保險推介、報告下載或業務引導服務。',
    'loading_msg': '載入中…',
    'error_load_fail': '載入失敗',
    'error_refresh_hint': '請重新整理頁面',
    'btn_reload': '重新載入',
    'top_stories': '今日要聞',
    'sub_free': '免費訂閱',
    'empty_articles': '沒有找到相關文章',
    'view_all_articles': '查看全部文章',
    'no_content': '暫無正文內容',
    'filter_btn_filter': '篩選',
    'filter_btn_close': '關閉',
    'filter_update': '數據更新',
    'no_data': '暫無精算備註',
    'tag_discontinued': '已停售',
    'tag_onsale': '在售',
    'sort_name_az': '產品名稱（A→Z）',
    'metric_covered': '保障病種',
    'metric_prem_years': '繳費年期',
    'metric_multi_pay': '多重賠付',
    'metric_annual_prem': '年繳保費',
    'article_loading': '正在載入…',
    'article_not_found': '文章未找到',
    'article_error_hint': '該文章可能已下架或連結有誤',
    'back_to_news': '返回 HiMiao讲堂',
    'related_products': '相關產品數據',
    'related_products_desc': '讀完情報，查閱精算審計過的客觀產品數據。',
    'cta_products': '進入產品審計庫 →',
    'submitting': '提交中…',
    'sub_fail': '訂閱失敗，請稍後重試',
    'article_no_slug': '未指定文章，請從 HiMiao讲堂 列表進入',
    'article_not_exist': '文章不存在或已下架',
    'no_more_articles': '暫無其他文章',
    'pd_load_ing': '正在載入產品數據…',
    'pd_load_fail': '載入失敗',
    'pd_not_found': '產品不存在或未發布',
    'pd_back': '← 返回產品庫',
    'pd_product_detail': '產品詳情',
    'pd_data_loading': '保司資訊載入中…',
    'pd_static_model': '【靜態模型聲明】本頁測算基於全市場統一標準樣本（30歲非吸煙男性），展示20年參考數據。不構成針對個人的財務適配建議。',
    'pd_type_whole_life': '終身壽險',
    'pd_type_critical_illness': '重疾險',
    'pd_meta_term': '條款版本',
    'pd_meta_denom': '計價資產',
    'pd_data_version': '數據版本',
    'pd_q1_body': '保司信用評級 {rating}，全球前10%。資產受香港保險業監管局監管，設有保單持有人保障基金。',
    'pd_q2_sub': '持有 20 年參考值',
    'pd_q2_sub_whole': '持有 20 年（含終身保障）',
    'pd_q2_sub_ci': '保障重症+早期危疾',
    'pd_q2_body_ci_multi': '覆蓋 <strong>{count}</strong> 種疾病，支持<strong>多重賠付</strong>，癌症可多次理賠。',
    'pd_q2_body_ci_single': '覆蓋 <strong>{count}</strong> 種疾病，單次賠付，理賠後保單終止。',
    'pd_q2_body': '年化收益率約 {irr}，含非保證紅利。具體收益參考精算審計指標。',
    'pd_q3_body': '前 {n} 年退保會虧損。前 {n} 年內退保將產生本金損失，請參閱現金價值表。',
    'pd_suit_c2_sub': '實際收益可能高於或低於演示值。',
    'pd_suit_c3_sub': '這款產品以美元計價，匯率會影響實際收益。',
    'pd_badge_div_savings': '分紅型',
    'pd_badge_div_life': '終身保障',
    'pd_rating_suffix': '評級',
    'pd_currency_usd': '美元',
    'pd_currency_hkd': '港元',
    'pd_ai_extract': '⚠ AI 輔助提取數據 — 本頁精算數值由 OCR 技術從官方文件中提取，可能存在細微偏差。',
    'pd_type_savings': '儲蓄險',
    'pd_usd': '美元計價',
    'pd_dividend': '分紅型',
    'pd_rating_aa': 'AA+ 評級',
    'pd_wechat': '微信諮詢',
    'pd_wechat_add': '添加微信，免費諮詢持牌顧問',
    'pd_close': '關閉',
    'pd_verdict': '精算審計結論',
    'pd_risk': '風險提示',
    'pd_baseline': '核心測算基準',
    'pd_baseline_sub': '統一靜態模型假設',
    'pd_label_gender': '性別',
    'pd_label_age': '年齡',
    'pd_label_smoke': '吸煙史',
    'pd_male': '男',
    'pd_female': '女',
    'pd_nonsmoke': '非吸煙',
    'pd_consult': '💬 諮詢持牌保險顧問',
    'pd_consult_desc': '數據僅供參考，個人情況差異較大。持牌顧問可為你提供合規的個人化評估。',
    'pd_wechat_cta': '🟢 微信免費諮詢 →',
    'pd_review': '精算備註',
    'pd_toast_compare': '請從產品庫選擇第二款產品，點擊「加入對比」即可開啟雙產品對比模式',
    'pd_toast_copied': '✓ 連結已複製',
    'pd_toast_manual': '請手動複製瀏覽器網址',
    'cmp_dim': '對比維度 / Comparison Metrics',
    'cmp_feature': '核心亮點',
    'cmp_score': '綜合評分',
    'cmp_currency': '保單幣種',
    'cmp_pending': '待更新',
    'cmp_no_data': '暫無數據',
    'cmp_pending_in': '待錄入',
    'cmp_support': '支持',
    'cmp_no_support': '不支持',
    'cmp_confirm': '待確認',
    'cmp_mixed_warn': '⚠ 當前對比包含不同險種產品，建議選擇同類產品以獲得精準對比維度',
    'cmp_basic': '基本資訊',
    'cmp_actuarial': '精算核心',
    'cmp_compliance': '合規披露',
    'cmp_features': '產品特色',
    'cmp_tags': '特色標籤',
    'cmp_coverage': '保障內容',
    'cmp_verdict': '精算辣評',
    'cmp_payment_term': '繳費年期',
    'cmp_irr20': '20年 IRR',
    'cmp_breakeven': '保證回本年',
    'cmp_fulfill5y': '近5年分紅實現率',
    'cmp_loan_ltv': '保單貸款上限',
    'cmp_annual_prem': '年繳保費',
    'cmp_conditions': '涵蓋重疾病種數',
    'cmp_multi_pay': '多重賠付',
    'cmp_view_audit': '查看審計詳情 →',
    'cmp_year_cash': '第{n}年現金價值'
  },
  en: {
    'act_compare': 'Compare',
    'act_contact': 'Email Us',
    'act_detail': 'Full Audit Report',
    'act_pdf': 'View at Official Source',
    'act_share': 'Share',
    'ai_greeting': 'Audit system ready. Upload a policy PDF or enter a product code (e.g. AIA-Wealth) and I\\\'ll calculate the real IRR for you.',
    'ai_placeholder': 'e.g. Analyze AIA 20-year IRR for me…',
    'breadcrumb_current': 'Compare',
    'breadcrumb_home': 'Home',
    'breadcrumb_products': 'Products',
    'btn_back': '← Back to Products',
    'btn_clear': 'Clear All',
    'btn_get': 'View Audit Report',
    'btn_pro': '📊 Pro Mode',
    'btn_read': 'Read Audit Report',
    'btn_simple': '😊 Plain Mode',
    'btn_view': 'View Audit Report',
    'btn_compare_start': 'Compare Selected',
    'tab_overview': 'Audit Overview',
    'tab_dna': 'Product DNA',
    'tab_archive': 'Core Archive',
    'scenario_opt': 'Optimistic',
    'scenario_neu': 'Neutral',
    'scenario_pes': 'Pessimistic',
    'btn_booking': '📋 Book Actuarial Consultation',
    'btn_auditor_bio': 'View Auditor Full Profile →',
    'btn_exit_compare': 'Exit Compare ✕',
    'pd_type_savings': 'Savings · USD',
    'pd_src_plan': 'AIA Official Illustration →',
    'pd_src_hkia': 'HKIA Dividend Fulfillment Report →',
    'pd_src_annual': 'AIA Annual Report 2023 →',
    'btn_triple_compare': 'Generate 3-Product Comparison →',
    'lbl_full_disclaimer': 'View Full Disclaimer →',
    'calc_breakeven': 'Breakeven',
    'calc_breakeven_val': 'Year 8',
    'calc_btn': 'Generate Report',
    'calc_budget': 'Annual Premium (USD)',
    'calc_duration': 'Duration',
    'calc_total': 'Total Value',
    'card1_desc': 'Breakeven in 4 years — fastest in market. Early liquidity window suits short-to-medium term holders.',
    'card1_metric': 'Breakeven: 4 Yrs',
    'card1_title': 'YF Life · Rich Life Legacy',
    'card2_desc': 'British-style dividend, highest long-term IRR. Non-guaranteed portion above median; notable dividend volatility.',
    'card2_metric': '20yr IRR: 6.15%',
    'card2_title': 'Prudential · Wealth Together',
    'card3_desc': 'High dividends with liquidity lock-in risk. Up to 21% loss on early surrender (first 3 years); cash value breakeven Year 7.',
    'card3_metric': 'Up to 21% early surrender loss',
    'card3_title': 'AIA Wealth Prestige III · Liquidity Risk',
    'card_added': 'Added',
    'card_breakeven': 'Breakeven',
    'card_compare': 'Add to Compare',
    'card_irr': '-yr IRR',
    'card_irr_label': '20-yr IRR',
    'card_pay_prefix': 'Pay',
    'card_review_label': '⚖ Audit Verdict · ',
    'card_ribbon': 'Data Insight',
    'card_score': 'Score',
    'card_title': 'Asset Health Check',
    'card_view': 'View Audit Report',
    'cat_alert': '🔴 Warning',
    'cat_all': 'All',
    'cat_audit': '⚖ Product Audit',
    'cat_guide': '🧭 Beginner Guide',
    'cat_market': '📊 Market Intel',
    'cat_policy': '📋 Policy Analysis',
    'ci1_desc': 'Covers 108 conditions, multi-pay support, early CI claims independent, waiver mechanism complete.',
    'ci1_metric': 'Coverage: 108 Conditions',
    'ci1_title': 'Prudential PRUlife CI',
    'ci2_badge': 'Multi-Pay: Up to 300%',
    'ci2_desc': 'Additional cancer relapse payout, high multi-pay ceiling, preserves life coverage. Composite protection.',
    'ci2_metric': 'Multi-Pay: Up to 300%',
    'ci2_title': 'AIA Crisis Care Plus',
    'ci3_desc': 'Actuarial team continuously updating. Subscribe weekly for new in-depth CI audits.',
    'ci3_metric': 'Coming Soon',
    'ci3_title': 'More CI Audit Reports',
    'ci_btn_list': 'View CI Rankings',
    'ci_h2': 'Critical Illness Audit Rankings',
    'ci_sub': 'Conditions covered · Multi-pay · Early stage',
    'clear_all': '✕  Clear All Filters',
    'clear_filter': 'Clear Filters',
    'col_add': 'Add Product',
    'col_add_sub': 'Can add',
    'col_add_unit': 'more',
    'col_remove': 'Remove',
    'contact_label': 'Contact Us',
    'cta_browse': 'Browse Products',
    'cta_email': '📮 Email Us',
    'cta_h': 'Need more product data?',
    'cta_method': 'View Methodology',
    'cta_pro': 'View Full Data →',
    'cta_sub': 'Browse the full actuarial database. All data sourced from official insurer disclosures.',
    'disclaimer_contact': ' · For any questions about this statement, contact',
    'disclaimer_updated': 'Last updated: February 2026',
    'empty_btn': 'Browse Products',
    'empty_msg': 'No matching products found',
    'filter_co': 'Insurer',
    'filter_currency': 'Currency',
    'filter_launch_year': 'Launch Year',
    'filter_score': 'Min Score',
    'filter_title': 'Type',
    'footer_about_desc': 'HiMiao provides neutral, objective insurance product audits. We do not represent any insurer or offer investment advice. All data from official insurer disclosures.',
    'footer_about_title': 'About HiMiao Audit',
    'footer_contact': 'Contact Us',
    'footer_copyright': '© 2026 HiMiao. Global Vision, Actuarial Future.',
    'footer_disclaimer': 'This material does not constitute any product solicitation or sales offer. For informational and educational purposes only.',
    'footer_privacy': 'Privacy Policy',
    'h1': 'Product Comparison',
    'h1_sub': 'Select 2–3 products to compare side by side. Green indicates higher value.',
    'hero_btn1': 'View Flagship Library',
    'hero_btn2': 'View Sample Report',
    'hero_h1': 'We don\'t sell insurance.<br>We tell the truth.',
    'hero_sub': 'HiMiao Audit is an independent third-party actuarial audit platform for Hong Kong insurance. In an industry full of sales pitches, we stand on the side of the consumer.',
    'hero_subtitle': 'More than insurance. Through global actuarial audits, we build a purchasing power fortress for you.',
    'hero_title': 'Lock in a Certain Future <br>in <span class="text-himiao">Uncertain</span> Times',
    'hero_trust': '49 Products · 13 Insurers · Independent Data',
    'hot_label': 'Hot This Week',
    'latest_label': '🔥 Top Stories',
    'kpi_breakeven_label': 'Breakeven',
    'kpi_breakeven_sub': 'Early exit = loss',
    'kpi_fulfill_label': 'Dividend Rate',
    'kpi_fulfill_sub': '5-yr avg fulfillment',
    'kpi_irr_label': '20-yr IRR',
    'kpi_irr_sub': 'Incl. non-guaranteed',
    'kpi_prem_label': 'Payment Period',
    'kpi_prem_sub': 'No further premiums',
    'kpi_illness_label': 'Conditions',
    'kpi_illness_sub': 'Covered conditions',
    'kpi_early_label': 'Multi-pay',
    'kpi_early_sub': 'Multi-pay support',
    'kpi_rating_label': 'Insurer Rating',
    'kpi_rating_sub': 'Credit rating',
    'kpi_loan_label': 'Loan LTV',
    'kpi_loan_sub': 'Max loan-to-value',
    'kpi_irr_sub_whole': 'Incl. whole life cover',
    'pd_breakeven_year_fmt': 'Year {n}',
    'pd_growth_mult_fmt': '~{x}x',
    'lbl_15yr': '15yr',
    'lbl_4yr': '4yr',
    'lbl_breakeven': 'Breakeven Year',
    'lbl_breakeven_sub': 'Years until capital recovery',
    'lbl_compare_hint': 'Select competitors from product library to compare',
    'lbl_compare_peer': 'Peer Product Comparison',
    'lbl_coming_soon': 'Coming Soon',
    'lbl_features': 'Key Features',
    'lbl_fulfill': '5-Year Dividend Fulfillment',
    'lbl_fulfill_sub': 'vs. illustrated rate',
    'lbl_irr': '20-Year IRR',
    'lbl_irr_sub': 'Internal Rate of Return',
    'lbl_ltv': 'Policy Loan LTV',
    'lbl_ltv_sub': 'Max loan-to-value',
    'lbl_nonguarant': 'Non-Guaranteed Ratio',
    'lbl_nonguarant_sub': 'Lower = less risk',
    'lbl_payment': 'Payment Period',
    'lbl_payment_sub': 'Payment Period',
    'lbl_review_tag': '⚖ HiMiao Audit Review',
    'lbl_score': 'Overall Score',
    'lbl_score_sub': 'HiMiao Score',
    'lbl_selected_cmp': 'Compare',
    'lbl_tags': 'Product Tags',
    'list_method': 'View Methodology',
    'list_note': '* Based on HiMiao Open Audit Model',
    'list_title': '2026 Actuarial Product Library',
    'modal_added': 'Added',
    'modal_title': 'Add Product to Compare',
    'nav_about': 'About',
    'nav_assets': 'Asset Shield',
    'nav_health': 'Health Audit',
    'nav_home': 'Home',
    'nav_intel': 'Intel',
    'nav_legacy': 'Legacy',
    'nav_news': 'Intel',
    'nav_academy': 'HiMiao Academy',
    'nav_products': 'Products',
    'news1_desc': 'How will the Fed\\\'s next move impact dividend fulfillment ratios?',
    'news1_title': 'What Trump\\\'s Return Means for Your USD Policies',
    'news2_meta': '2 Hours Ago · Savings Audit Team',
    'news2_tag': 'Alert',
    'news2_title': 'Alert: This "Viral" Savings Plan\\\'s Breakeven Delayed by 3 Years',
    'news3_meta': '1 Day Ago · Medical Team',
    'news3_tag': 'Report',
    'news3_title': '2026 HK CI Insurance Audit: Do You Really Need "Multi-Pay"?',
    'news_main_title': 'HiMiao Academy',
    'news_page_h1': 'Market News',
    'news_view_all': 'Enter Academy',
    'next_page': 'Next →',
    'page_h1': 'Global Product Audit Library',
    'page_sub': 'Independently produced by HiMiao Actuarial Team · No sales · Only truth',
    'page_title': 'About HiMiao | Independent Actuarial Audit Platform',
    'prev_page': '← Prev',
    'q1_ans': 'Very Safe',
    'q1_label': '① Is it safe?',
    'q2_label': '② Will my money grow?',
    'q3_ans': 'Not liquid in early years',
    'q3_label': '③ What are the risks?',
    'read_full': 'Read Full Audit →',
    'result_count': 'Showing {n} products',
    'search_ph': 'Search articles…',
    'sub_ph': 'your@email.com',
    'sec_actuarial': 'Actuarial Data',
    'sec_basic': 'Basic Info',
    'sec_compliance': 'Compliance Disclosures',
    'sec_features': 'Key Features',
    'sec_review': 'Audit Review',
    'sort_breakeven': 'Breakeven (Fast→Slow)',
    'sort_irr': '20-yr IRR (High→Low)',
    'sort_score': 'Score (High→Low)',
    'stat1': 'Products Audited',
    'stat2': 'Avg. Actuary Years',
    'stat3': 'Insurer Partnerships',
    'stat4': 'Insurance Categories',
    'sub_btn': 'Subscribe',
    'sub_err': 'Please enter a valid email address',
    'sub_success': '✓ Subscribed!',
    'sub_desc': 'Weekly updates. No spam, just hard data.',
    'sub_h': 'Subscribe Weekly',
    'sub_note': '2,847 readers · Unsubscribe anytime',
    'sub_title': 'Subscribe Newsletter',
    'suit_c1': 'Can hold 10+ years',
    'suit_c1_sub': 'This fund won\'t be needed for 10 years',
    'suit_c2': 'Accept non-guaranteed dividend volatility',
    'suit_c3': 'Comfortable holding USD assets',
    'suit_h': 'Is This Right for Me?',
    'suit_sub': '3 questions, 30 seconds',
    'tab_ci': 'Critical Illness',
    'tab_whole_life': 'Whole Life',
    'tab_wholelife': 'Whole Life',
    'tab_savings': 'Savings',
    'toast_dupe': 'Product already in comparison',
    'toast_max': 'Maximum 3 products to compare',
    'toast_min_select': 'Please select at least 2 products to compare',
    'val_higher': '▲ Higher value',
    'val_lower': '▼ Lower value',
    'val_year': 'yr',
    'card2_badge': 'British Dividend · IRR Upper Quartile',
    'card3_badge': '⚠ High Early Surrender Loss',
    'card3_tooltip': 'Trigger: Year 1–3 cumulative cash value &lt; 79% of premiums paid.<br>Source: Official insurer illustration',
    'calc_model_badge': 'Static Model · Age 30 · Male · Non-Smoker',
    'calc_disclaimer': 'This projection uses a unified actuarial model and does not constitute financial advice.',
    'footer_nav_title': 'Navigation',
    'footer_contact_title': 'Contact',
    'wl1_title': 'AIA WealthChoice (Terminating Bonus)',
    'wl1_desc': '10-year payment. Cash value reaches ~21.7x premiums paid by year 70. Strong long-term compounding; terminating bonus is non-lockable.',
    'wl1_metric': 'Year 70: 21.7x Premium Paid',
    'wl1_btn': 'View Whole Life Data',
    'wl2_badge': 'Lockable Bonus · Stable Death Benefit',
    'wl2_title': 'SunLife Succession II',
    'wl2_desc': 'Annual + terminating dividends. Terminating bonus lockable for growth. Death benefit never decreases. Strong legacy planning profile.',
    'wl2_metric': '30yr: 2.9x · 70yr: 14x+',
    'wl3_badge': '⚠ Death Benefit May Decrease',
    'wl3_company': 'WHOLE LIFE · Select Products',
    'wl3_title': 'Death Benefit Reduction Clause',
    'wl3_desc': 'Some whole life plans reduce death benefit in later years — potentially below 50% of sum insured. Suitable for savings-focused policyholders.',
    'wl3_metric': 'Min: 50% of Sum Insured',
    'wl3_btn': 'View Full Data',
    'ci3_waiting_badge': '⚠ Note: Waiting Periods',
    'ci3_waiting_company': 'CI · Data Observation',
    'ci3_waiting_title': 'Waiting Period & Year-1 Exclusions',
    'ci3_waiting_desc': 'Among our 11 CI products, standard waiting period is 90 days; some cancer riders extend to 180 days. Diagnosis date calculation varies by insurer.',
    'ci3_waiting_metric': 'Waiting Period: 90–180 Days',
    'ci3_waiting_btn': 'View Full Data Comparison',
    'why_h2': 'Hong Kong Insurance Market:<br>Severe Information Asymmetry',
    'why_label': 'Why We Exist',
    'about_hero_label': 'About HiMiao',
    'about_why_p1': 'A savings or participating plan illustration can run dozens to hundreds of pages. Guaranteed and non-guaranteed figures are mixed; IRR is often obscured; breakeven definitions differ by insurer.',
    'about_why_p2': 'Ordinary consumers lack the time, tools, and actuarial knowledge to cut through this. They rely on brokers—whose income comes from commissions.',
    'about_why_p3': 'HiMiao exists to break that cycle. We are the consumer’s actuary in this market.',
    'about_principles_label': 'Core Principles',
    'about_p1_title': 'Data Before Opinion',
    'about_p1_desc': 'Every conclusion comes from calculation, not judgment. Every number has a traceable source.',
    'about_p2_title': 'No Sales Stance',
    'about_p2_desc': 'No commission share. We call strengths and risks as they are.',
    'about_p3_title': 'Understandable to Everyone',
    'about_p3_desc': 'We translate actuarial results into language anyone can understand.',
    'about_p4_title': 'Always Up to Date',
    'about_p4_desc': 'We sync with insurer updates and do not publish outdated audit reports.',
    'about_process_label': 'Audit Process',
    'about_process_h2': 'Every audit report<br>passes four checkpoints',
    'about_process_intro': 'From raw illustrations to product library display, our process is triple-checked by actuaries, data engineers, and an AI engine to ensure every figure is accurate.',
    'about_step1_title': 'Capture & Digitize',
    'about_step1_desc': 'We extract raw data from insurers’ official benefit illustrations and strictly separate guaranteed and non-guaranteed columns.',
    'about_step2_title': 'Manual Clean & Verify',
    'about_step2_desc': 'Data staff line-check against source documents, correct OCR errors, and ensure year–value alignment to prevent misalignment.',
    'about_step3_title': 'AI Actuarial Check',
    'about_step3_badge': 'Core Moat',
    'about_step3_desc': 'Our engine back-calculates IRR, checks curve smoothness, and validates breakeven. Fails are sent back for re-audit.',
    'about_step4_title': 'Auto Publish',
    'about_step4_desc': 'After passing checks, we generate standardized JSON and push to the product library. End-to-end in as little as 24 hours.',
    'about_contact_h2': 'Questions? Get in Touch',
    'about_contact_intro': 'Whether it’s data corrections, audit collaboration, or learning about HiMiao—we’re here.',
    'about_contact_email': 'Email',
    'about_contact_email_reply': 'Usually replied within 24–48 hours',
    'about_contact_wechat': 'WeChat',
    'about_contact_wechat_qr': 'Scan to add, note “HiMiao”',
    'about_contact_we_response': 'What we respond to',
    'about_contact_ok1': 'Product data corrections',
    'about_contact_ok2': 'Actuarial audit collaboration',
    'about_contact_ok3': 'Media use and licensing',
    'about_contact_ok4': 'Broker platform partnerships',
    'about_contact_no': 'Product sales (we do not offer)',
    'about_disc_label': 'Legal & Disclaimer',
    'about_disc_h2': 'Full Disclaimer',
    'about_disc_1_h3': '1 · Nature of Platform',
    'about_disc_1_p': 'HiMiao Audit (“the Platform”) is an independent third-party insurance information audit platform operated by the HiMiao team. The Platform has no sales partnership, commission sharing, or interest alignment with any licensed insurer, broker, or agent.',
    'about_disc_2_h3': '2 · Nature and Use of Information',
    'about_disc_2_p': 'All content on the Platform (including but not limited to audit reports, actuarial data, IRR results, scoring, editorial comments, and intel articles) is for general information only. It does not constitute investment, financial, or insurance advice, or any solicitation or recommendation of insurance products.',
    'about_disc_3_h3': '3 · Data Sources and Accuracy',
    'about_disc_3_p': 'Platform data is mainly from insurers’ official benefit illustrations and HKIA public disclosures. We take reasonable care but do not warrant completeness, timeliness, or accuracy. Product terms and dividend assumptions may change; please refer to insurers’ latest official documents.',
    'about_disc_4_h3': '4 · IRR and Illustrations',
    'about_disc_4_p': 'IRR and cash value illustrations shown are based on specific assumptions and include non-guaranteed elements. Non-guaranteed figures do not represent actual future results; past fulfillment rates do not guarantee or predict future performance.',
    'about_disc_5_h3': '5 · Professional Advice',
    'about_disc_5_p': 'Before any insurance purchase decision, seek independent advice from a licensed advisor or financial planner and read the full policy terms.',
    'about_disc_6_h3': '6 · Intellectual Property',
    'about_disc_6_p': 'All original content is owned by the HiMiao team. No copying, republication, or commercial use without written permission. For media use, contact',
    'about_disc_7_h3': '7 · Privacy',
    'about_disc_7_p': 'User data (including subscription email) is used only for Platform updates. We do not sell, transfer, or disclose to third parties for commercial use. You may request deletion at any time. We do not use tracking ad cookies.',
    'about_disc_8_h3': '8 · Governing Law',
    'about_disc_8_p': 'Terms and disclaimers are governed by the laws of Hong Kong SAR. Any dispute shall be subject to the exclusive jurisdiction of the courts of Hong Kong SAR.',
    'about_region_banner': '【Regional Notice】This platform provides actuarial data display only and does not offer insurance services, report downloads or business guidance in Mainland China.',
    'loading_msg': 'Loading…',
    'error_load_fail': 'Load failed',
    'error_refresh_hint': 'Please refresh and try again',
    'btn_reload': 'Retry',
    'top_stories': 'Top Stories',
    'sub_free': 'Subscribe Free',
    'empty_articles': 'No articles found',
    'view_all_articles': 'View All',
    'no_content': 'No content available',
    'filter_btn_filter': 'Filter',
    'filter_btn_close': 'Close',
    'filter_update': 'Data updated',
    'no_data': 'No audit note',
    'tag_discontinued': 'Discontinued',
    'tag_onsale': 'On Sale',
    'sort_name_az': 'Name (A→Z)',
    'metric_covered': 'Conditions',
    'metric_prem_years': 'Pay Period',
    'metric_multi_pay': 'Multi-Pay',
    'metric_annual_prem': 'Annual Premium',
    'article_loading': 'Loading…',
    'article_not_found': 'Article not found',
    'article_error_hint': 'This article may have been removed or the link is invalid',
    'back_to_news': 'Back to HiMiao Academy',
    'related_products': 'Product Data',
    'related_products_desc': 'Browse actuarial audit data after reading.',
    'cta_products': 'View Product Library →',
    'submitting': 'Submitting…',
    'sub_fail': 'Subscribe failed, please try again later',
    'article_no_slug': 'No article specified. Open from HiMiao Academy list.',
    'article_not_exist': 'Article not found or has been removed',
    'no_more_articles': 'No more articles',
    'pd_load_ing': 'Loading product…',
    'pd_load_fail': 'Load failed',
    'pd_not_found': 'Product not found or unpublished',
    'pd_back': '← Back to Products',
    'pd_product_detail': 'Product Detail',
    'pd_data_loading': 'Loading insurer info…',
    'pd_static_model': '[Static Model] This page uses a unified standard sample (male, 30, non-smoker) for 20-year projections. Not personal financial advice.',
    'pd_type_whole_life': 'Whole Life',
    'pd_type_critical_illness': 'Critical Illness',
    'pd_meta_term': 'Term version',
    'pd_meta_denom': 'denominated',
    'pd_data_version': 'Data version',
    'pd_q1_body': 'Insurer credit rating {rating}, global top 10%. Assets supervised by HKIA, with policyholder protection fund.',
    'pd_q2_sub': '20-year reference',
    'pd_q2_sub_whole': '20-year hold (incl. whole life cover)',
    'pd_q2_sub_ci': 'Critical + early CI cover',
    'pd_q2_body_ci_multi': 'Covers <strong>{count}</strong> conditions; <strong>multi-pay</strong> supported, cancer can be claimed multiple times.',
    'pd_q2_body_ci_single': 'Covers <strong>{count}</strong> conditions; single pay, policy ends after claim.',
    'pd_q2_body': 'Annual yield approx. {irr}, incl. non-guaranteed. See audit metrics for details.',
    'pd_q3_body': 'Surrender in the first {n} years incurs a loss. See cash value table.',
    'pd_suit_c2_sub': 'Actual returns may be higher or lower than illustrated.',
    'pd_suit_c3_sub': 'This product is USD-denominated; exchange rate affects actual returns.',
    'pd_badge_div_savings': 'Participating',
    'pd_badge_div_life': 'Lifetime cover',
    'pd_rating_suffix': 'Rating',
    'pd_currency_usd': 'USD',
    'pd_currency_hkd': 'HKD',
    'pd_ai_extract': '⚠ AI-assisted data extraction. Figures may have minor variances. Refer to official illustrations for precise values.',
    'pd_type_savings': 'Savings',
    'pd_usd': 'USD',
    'pd_dividend': 'Dividend',
    'pd_rating_aa': 'AA+ Rating',
    'pd_wechat': 'WeChat Consult',
    'pd_wechat_add': 'Add WeChat for free advisor consultation',
    'pd_close': 'Close',
    'pd_verdict': 'Audit Conclusion',
    'pd_risk': 'Risk Notice',
    'pd_baseline': 'Core Model',
    'pd_baseline_sub': 'Unified Static Assumptions',
    'pd_label_gender': 'Gender',
    'pd_label_age': 'Age',
    'pd_label_smoke': 'Smoking',
    'pd_male': 'Male',
    'pd_female': 'Female',
    'pd_nonsmoke': 'Non-Smoker',
    'pd_consult': '💬 Talk to Licensed Advisor',
    'pd_consult_desc': 'Data for reference only. Licensed advisors can provide personalized assessment.',
    'pd_wechat_cta': '🟢 Free WeChat Consult →',
    'pd_review': 'Audit Note',
    'pd_toast_compare': 'Select a second product from the library and click Add to Compare',
    'pd_toast_copied': '✓ Link copied',
    'pd_toast_manual': 'Please copy the URL manually',
    'cmp_dim': 'Comparison Metrics',
    'cmp_feature': 'Key Features',
    'cmp_score': 'Overall Score',
    'cmp_currency': 'Currency',
    'cmp_pending': 'Pending',
    'cmp_no_data': 'No data',
    'cmp_pending_in': 'Pending',
    'cmp_support': 'Yes',
    'cmp_no_support': 'No',
    'cmp_confirm': 'TBD',
    'cmp_mixed_warn': '⚠ Products from different categories. Select same type for accurate comparison.',
    'cmp_basic': 'Basic Info',
    'cmp_actuarial': 'Actuarial Core',
    'cmp_compliance': 'Compliance',
    'cmp_features': 'Product Features',
    'cmp_tags': 'Product Tags',
    'cmp_coverage': 'Coverage',
    'cmp_verdict': 'Audit Verdict',
    'cmp_payment_term': 'Payment Term',
    'cmp_irr20': '20yr IRR',
    'cmp_breakeven': 'Breakeven Year',
    'cmp_fulfill5y': '5Y Dividend Fulfillment',
    'cmp_loan_ltv': 'Policy Loan LTV',
    'cmp_annual_prem': 'Annual Premium',
    'cmp_conditions': 'Conditions Covered',
    'cmp_multi_pay': 'Multi-Pay',
    'cmp_view_audit': 'View Audit →',
    'cmp_year_cash': 'Year {n} Cash Value'
  }
};
