"""
app/models/product_sub.py
储蓄险 / 终身寿险 / 重疾险 子表 ORM（只读，用于 API 合并输出）
"""
from sqlalchemy import Column, Integer, Float, Boolean, Text, String, JSON, Date
from app.db.base import Base


class SavingsProduct(Base):
    """储蓄分红险子表 — 对应 savings_products"""
    __tablename__ = "savings_products"
    __table_args__ = {"extend_existing": True}

    id = Column(Integer, primary_key=True, autoincrement=True)
    product_id = Column(Integer, nullable=False, unique=True)

    coverage_period = Column(String(32), nullable=True)
    death_benefit_formula = Column(Text, nullable=True)
    guaranteed_death_benefit_pct = Column(Float, nullable=True)
    premium_payment_terms_json = Column(JSON, nullable=True)
    premium_holiday_available = Column(Boolean, default=False)
    premium_holiday_max_years = Column(Integer, nullable=True)
    currency_options_json = Column(JSON, nullable=True)
    currency_count = Column(Integer, nullable=True)
    currency_switch_available = Column(Boolean, default=False)
    currency_switch_from_year = Column(Integer, nullable=True)
    second_insured = Column(Boolean, default=False)
    change_insured = Column(Boolean, default=False)
    change_insured_from_year = Column(Integer, nullable=True)
    policy_split = Column(Boolean, default=False)
    policy_split_from_year = Column(Integer, nullable=True)
    policy_successor = Column(Boolean, default=False)
    policy_trustee = Column(Boolean, default=False)
    dividend_lock = Column(Boolean, default=False)
    dividend_lock_from_year = Column(Integer, nullable=True)
    dividend_lock_max_pct = Column(Float, nullable=True)
    dividend_unlock = Column(Boolean, default=False)
    income_option = Column(Boolean, default=False)
    waiver_of_premium = Column(Boolean, default=False)
    waiver_condition = Column(String(128), nullable=True)
    accidental_death_extra = Column(Boolean, default=False)
    accidental_death_period_years = Column(Integer, nullable=True)
    accidental_death_pct = Column(Float, nullable=True)
    terminal_illness_benefit = Column(Boolean, default=False)
    special_features_json = Column(JSON, nullable=True)
    illustration_age = Column(Integer, default=30)
    illustration_gender = Column(String(4), default="F")
    illustration_annual_premium = Column(Float, default=100000)
    illustration_total_premium = Column(Float, default=500000)
    illustration_payment_term = Column(Integer, default=5)
    illustration_date = Column(Date, nullable=True)
    sv_y1 = Column(Float, nullable=True)
    sv_y2 = Column(Float, nullable=True)
    sv_y3 = Column(Float, nullable=True)
    sv_y4 = Column(Float, nullable=True)
    sv_y5 = Column(Float, nullable=True)
    sv_y6 = Column(Float, nullable=True)
    sv_y7 = Column(Float, nullable=True)
    sv_y8 = Column(Float, nullable=True)
    sv_y9 = Column(Float, nullable=True)
    sv_y10 = Column(Float, nullable=True)
    sv_y15 = Column(Float, nullable=True)
    sv_y20 = Column(Float, nullable=True)
    sv_y25 = Column(Float, nullable=True)
    sv_y30 = Column(Float, nullable=True)
    sv_age65 = Column(Float, nullable=True)
    sv_age70 = Column(Float, nullable=True)
    sv_age75 = Column(Float, nullable=True)
    sv_age80 = Column(Float, nullable=True)
    sv_age90 = Column(Float, nullable=True)
    sv_age100 = Column(Float, nullable=True)
    db_y1 = Column(Float, nullable=True)
    db_y5 = Column(Float, nullable=True)
    db_y10 = Column(Float, nullable=True)
    db_y20 = Column(Float, nullable=True)
    db_y30 = Column(Float, nullable=True)
    db_age65 = Column(Float, nullable=True)
    db_age100 = Column(Float, nullable=True)
    gcv_y5 = Column(Float, nullable=True)
    gcv_y10 = Column(Float, nullable=True)
    gcv_y20 = Column(Float, nullable=True)
    gcv_y30 = Column(Float, nullable=True)
    data_flag = Column(String(32), nullable=True)
    data_note = Column(Text, nullable=True)
    data_source = Column(String(128), nullable=True)


class WholelifeProduct(Base):
    """终身寿险子表 — 对应 wholelife_products"""
    __tablename__ = "wholelife_products"
    __table_args__ = {"extend_existing": True}

    id = Column(Integer, primary_key=True, autoincrement=True)
    product_id = Column(Integer, nullable=False, unique=True)

    illustration_age = Column(Integer, default=30)
    illustration_gender = Column(String(4), default="F")
    illustration_sum_assured = Column(Float, default=1000000)
    illustration_payment_term = Column(Integer, default=10)
    illustration_annual_premium = Column(Float, nullable=True)
    illustration_total_premium = Column(Float, nullable=True)
    illustration_date = Column(Date, nullable=True)
    coverage_period = Column(String(32), nullable=True)
    surrender_value_formula = Column(Text, nullable=True)
    death_benefit_formula = Column(Text, nullable=True)
    death_benefit_guaranteed_pct_initial = Column(Float, nullable=True)
    death_benefit_taper_start_age = Column(Integer, nullable=True)
    death_benefit_taper_floor_pct = Column(Float, nullable=True)
    extra_death_benefit = Column(Boolean, default=False)
    extra_death_benefit_desc = Column(Text, nullable=True)
    premium_waiver = Column(Boolean, default=False)
    premium_waiver_condition = Column(Text, nullable=True)
    dividend_type = Column(String(32), nullable=True)
    dividend_lock = Column(Boolean, default=False)
    dividend_lock_from_year = Column(Integer, nullable=True)
    dividend_lock_max_pct = Column(Float, nullable=True)
    reverse_mortgage = Column(Boolean, default=False)
    inflation_top_up = Column(Boolean, default=False)
    terminal_illness_advance = Column(Boolean, default=False)
    change_insured = Column(Boolean, default=False)
    policy_successor = Column(Boolean, default=False)
    special_features_json = Column(JSON, nullable=True)
    y10_gcv = Column(Float, nullable=True)
    y10_div = Column(Float, nullable=True)
    y10_csv = Column(Float, nullable=True)
    y10_da = Column(Float, nullable=True)
    y15_gcv = Column(Float, nullable=True)
    y15_div = Column(Float, nullable=True)
    y15_csv = Column(Float, nullable=True)
    y15_da = Column(Float, nullable=True)
    y20_gcv = Column(Float, nullable=True)
    y20_div = Column(Float, nullable=True)
    y20_csv = Column(Float, nullable=True)
    y20_da = Column(Float, nullable=True)
    y25_gcv = Column(Float, nullable=True)
    y25_div = Column(Float, nullable=True)
    y25_csv = Column(Float, nullable=True)
    y25_da = Column(Float, nullable=True)
    y30_gcv = Column(Float, nullable=True)
    y30_div = Column(Float, nullable=True)
    y30_csv = Column(Float, nullable=True)
    y30_da = Column(Float, nullable=True)
    y35_gcv = Column(Float, nullable=True)
    y35_div = Column(Float, nullable=True)
    y35_csv = Column(Float, nullable=True)
    y35_da = Column(Float, nullable=True)
    y40_gcv = Column(Float, nullable=True)
    y40_div = Column(Float, nullable=True)
    y40_csv = Column(Float, nullable=True)
    y40_da = Column(Float, nullable=True)
    y50_gcv = Column(Float, nullable=True)
    y50_div = Column(Float, nullable=True)
    y50_csv = Column(Float, nullable=True)
    y50_da = Column(Float, nullable=True)
    y60_gcv = Column(Float, nullable=True)
    y60_div = Column(Float, nullable=True)
    y60_csv = Column(Float, nullable=True)
    y60_da = Column(Float, nullable=True)
    y70_gcv = Column(Float, nullable=True)
    y70_div = Column(Float, nullable=True)
    y70_csv = Column(Float, nullable=True)
    y70_da = Column(Float, nullable=True)
    data_source = Column(String(128), nullable=True)


class CiProduct(Base):
    """重疾险子表 — 对应 ci_products"""
    __tablename__ = "ci_products"
    __table_args__ = {"extend_existing": True}

    id = Column(Integer, primary_key=True, autoincrement=True)
    product_id = Column(Integer, nullable=False, unique=True)

    illustration_age = Column(Integer, default=30)
    illustration_gender = Column(String(4), default="F")
    illustration_sum_assured = Column(Float, default=1000000)
    illustration_payment_term = Column(Integer, default=20)
    illustration_annual_premium = Column(Float, nullable=True)
    illustration_total_premium = Column(Float, nullable=True)
    illustration_date = Column(Date, nullable=True)
    coverage_period = Column(String(32), nullable=True)
    waiting_period_days = Column(Integer, nullable=True)
    severe_ci_count = Column(Integer, nullable=True)
    severe_ci_payout = Column(Text, nullable=True)
    cancer_multi_pay = Column(Integer, nullable=True)
    cancer_multi_pay_pct = Column(Float, nullable=True)
    cancer_multi_pay_age_limit = Column(Integer, nullable=True)
    heart_stroke_multi_pay = Column(Integer, nullable=True)
    heart_stroke_multi_pay_pct = Column(Float, nullable=True)
    heart_stroke_multi_pay_age_limit = Column(Integer, nullable=True)
    alzheimer_pay = Column(Boolean, default=False)
    alzheimer_pay_pct = Column(Float, nullable=True)
    extra_payout_desc = Column(Text, nullable=True)
    early_ci_count = Column(Integer, nullable=True)
    children_ci_count = Column(Integer, nullable=True)
    early_ci_payout_pct = Column(Float, default=20.0)
    early_ci_payout_cap = Column(Float, nullable=True)
    premium_waiver_on_ci = Column(Boolean, default=False)
    premium_waiver_condition = Column(Text, nullable=True)
    maternity_option = Column(Boolean, default=False)
    maternity_option_name = Column(String(64), nullable=True)
    icu_benefit = Column(Boolean, default=False)
    terminal_illness_benefit = Column(Boolean, default=False)
    special_features_json = Column(JSON, nullable=True)
    y20_cv_g = Column(Float, nullable=True)
    y20_cv_ng = Column(Float, nullable=True)
    y20_ci_claim = Column(Float, nullable=True)
    y25_cv_g = Column(Float, nullable=True)
    y25_cv_ng = Column(Float, nullable=True)
    y25_ci_claim = Column(Float, nullable=True)
    y30_cv_g = Column(Float, nullable=True)
    y30_cv_ng = Column(Float, nullable=True)
    y30_ci_claim = Column(Float, nullable=True)
    y35_cv_g = Column(Float, nullable=True)
    y35_cv_ng = Column(Float, nullable=True)
    y35_ci_claim = Column(Float, nullable=True)
    y40_cv_g = Column(Float, nullable=True)
    y40_cv_ng = Column(Float, nullable=True)
    y40_ci_claim = Column(Float, nullable=True)
    y50_cv_g = Column(Float, nullable=True)
    y50_cv_ng = Column(Float, nullable=True)
    y50_ci_claim = Column(Float, nullable=True)
    age85_cv_g = Column(Float, nullable=True)
    age85_cv_ng = Column(Float, nullable=True)
    age85_ci_claim = Column(Float, nullable=True)
    age90_cv_g = Column(Float, nullable=True)
    age90_cv_ng = Column(Float, nullable=True)
    age90_ci_claim = Column(Float, nullable=True)
    age100_cv_g = Column(Float, nullable=True)
    age100_cv_ng = Column(Float, nullable=True)
    age100_ci_claim = Column(Float, nullable=True)
    data_source = Column(String(128), nullable=True)
